import type { Metadata } from "next";
import {  Sora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/layout/NavBar";
import { Toaster } from "sonner";
import Footer from "@/components/layout/Footer";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative h-full font-sans antialiased bg-gradient-to-r from-[#eefaed] to-[#f2f7fb]",
          sora.className
        )}
      >
        <main className="relative flex flex-col min-h-screen z-30">
            <NavBar />
            <div className="flex-grow flex-1 mb-6">{children}</div>
            <Footer />
        </main>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}