export const courses = [
    {
      id: 1,
      name: "Web Design (HTML, CSS, JavaScript)",
      description: "Unlock the power of the web by mastering HTML, CSS, and JavaScript—the core technologies behind every modern website.",
      details: "Unlock the power of the web by mastering HTML, CSS, and JavaScript—the core technologies behind every modern website. Whether you’re a beginner or looking to refine your skills, we equip you with hands-on projects and real-world applications to launch your career in web design. Start building the web today!",
      image: "/courses/web-design.jpg",
      price: "130,000",
      category: "Web",
    },
    {
      id: 2,
      name: "Web Development - Backend (Node.js)",
      description: "Power the web with Node.js, the backbone of modern, high-performance web applications! At RoyalEcho Academy, you’ll learn how to build fast, scalable, and secure backend systems using Node.js, Express.js, and databases.",
      details: "Power the web with Node.js, the backbone of modern, high-performance web applications! At RoyalEcho Academy, you’ll learn how to build fast, scalable, and secure backend systems using Node.js, Express.js, and databases. From handling user authentication to creating robust APIs, this course equips you with real-world skills to develop full-fledged web applications. Whether you're starting fresh or expanding your expertise, our hands-on approach ensures you gain practical experience to thrive as a backend developer.",
      image: "/courses/web-design.jpg",
      price: "150,000",
      category: "Web",
    },
    {
      id: 3,
      name: "Web Development - Backend (Nest.js)",
      description: "Designed for both beginners and experienced developers, this course will elevate your backend skills and prepare you for high-demand careers in web development.",
      details: "Build enterprise-grade backend systems with Nest.js, the powerful framework for scalable and maintainable server-side applications! At RoyalEcho Academy, you’ll master TypeScript, dependency injection, modular architecture, and API development while working with databases, authentication, and real-world integrations. Write cleaner, more efficient code—start your journey with Nest.js today! ",
      image: "/courses/web-design.jpg",
      price: "150,000",
      category: "Web",
    },
    {
      id: 4,
      name: "Web Design - Advanced (ReactJs)",
      description: "Take your web design skills to the next level with React.js, the leading library for building fast, interactive, and dynamic user interfaces. You'll master component-based architecture, state management, hooks, and performance optimization",
      details: "Whether you're upgrading your skills or aiming for a career in modern web development, this course will set you apart. Learn how to craft seamless user experiences with reusable components and real-world projects.Take your web design skills to the next level with React.js, the leading library for building fast, interactive, and dynamic user interfaces! At RoyalEcho Academy, you'll master component-based architecture, state management, hooks, and performance optimization to create stunning, high-performing web applications.",
      image: "/courses/web-design.jpg",
      price: "200,000",
      category: "Web",
    },
    {
      id: 5,
      name: "Web Development - Advanced (NextJs)",
      description: "Supercharge your web development skills with Next.js, the ultimate React framework for building lightning-fast, SEO-friendly, and scalable web applications.",
      details: "Dive deep into server-side rendering (SSR), static site generation (SSG), API routes, authentication, and performance optimization. Learn how to build modern, production-ready applications with seamless user experiences. Whether you're leveling up your skills or preparing for high-demand web development roles, this course will give you the edge. Build smarter, ship faster—master Next.js today!",
      image: "/courses/web-design.jpg",
      price: "220,000",
      category: "Web",
    },
    {
      id: 6,
      name: "Python",
      description: "Master Python, the world’s most versatile and beginner-friendly programming language! At RoyalEcho Academy, you'll learn everything from the fundamentals to advanced concepts.",
      details: "Whether you’re coding your first script or aiming to build powerful applications, this course provides hands-on projects and real-world use cases to help you succeed. Unlock endless possibilities—start your Python journey today!",
      image: "/courses/web-design.jpg",
      price: "200,000",
      category: "Programming Languages",
    },
    {
      id: 7,
      name: "C++",
      description: "Learn C++, the powerhouse language behind high-performance software, game development, and system programming.",
      details: "you'll master object-oriented programming (OOP), data structures, algorithms, memory management, and more. Whether you're diving into competitive programming, software development, or low-level system design, this course equips you with the skills to write efficient, optimized code.",
      image: "/courses/web-design.jpg",
      price: "250,000",
      category: "Programming Languages",
    },
    {
      id: 8,
      name: "UI/UX",
      description: "Supercharge your web development skills with Next.js, the ultimate React framework for building lightning-fast, SEO-friendly, and scalable web applications.",
      details: "Dive deep into server-side rendering (SSR), static site generation (SSG), API routes, authentication, and performance optimization. Learn how to build modern, production-ready applications with seamless user experiences. Whether you're leveling up your skills or preparing for high-demand web development roles, this course will give you the edge. Build smarter, ship faster—master Next.js today!",
      image: "/courses/web-design.jpg",
      price: "250,000",
      category: "Design",
    },
    {
      id: 9,
      name: "Graphic Design",
      description: "Supercharge your web development skills with Next.js, the ultimate React framework for building lightning-fast, SEO-friendly, and scalable web applications.",
      details: "Dive deep into server-side rendering (SSR), static site generation (SSG), API routes, authentication, and performance optimization. Learn how to build modern, production-ready applications with seamless user experiences. Whether you're leveling up your skills or preparing for high-demand web development roles, this course will give you the edge. Build smarter, ship faster—master Next.js today!",
      image: "/courses/web-design.jpg",
      price: "250,000",
      category: "Design",
    },
    {
      id: 10,
      name: "Data Analysis",
      description: "Supercharge your web development skills with Next.js, the ultimate React framework for building lightning-fast, SEO-friendly, and scalable web applications.",
      details: "Dive deep into server-side rendering (SSR), static site generation (SSG), API routes, authentication, and performance optimization. Learn how to build modern, production-ready applications with seamless user experiences. Whether you're leveling up your skills or preparing for high-demand web development roles, this course will give you the edge. Build smarter, ship faster—master Next.js today!",
      image: "/courses/web-design.jpg",
      price: "150,000",
      category: "Data",
    },
  ]
